import { createAdminClient } from "@/lib/supabase/admin";
import { inviteUser, setUserBan, setUserRole } from "./actions";

export default async function AdminUsers() {
  const admin=createAdminClient(); const { data, error }=await admin.auth.admin.listUsers({ page:1, perPage:200 }); if(error) throw error;
  const users=data.users;
  return <main className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Users</h1><p className="mt-2 text-gray-600">Invite users, promote admins and suspend access.</p></div><form action={inviteUser} className="flex gap-2"><input name="email" type="email" required placeholder="email@example.com" className="rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg bg-gray-950 px-4 py-2 text-sm font-bold text-white">Invite</button></form></div>
    <div className="mt-6 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b bg-gray-50 text-left text-xs uppercase text-gray-400"><th className="p-3">Email</th><th>Role</th><th>Created</th><th>Last sign-in</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map((u:any)=>{const role=u.app_metadata?.role||"reader"; const banned=Boolean(u.banned_until&&new Date(u.banned_until)>new Date());return <tr key={u.id} className="border-b last:border-0"><td className="p-3"><div className="font-bold">{u.email||u.phone||u.id}</div><div className="text-xs text-gray-400">{u.id}</div></td><td><form action={setUserRole} className="flex gap-2"><input type="hidden" name="user_id" value={u.id}/><select name="role" defaultValue={role} className="rounded-lg border px-2 py-1.5"><option value="reader">Reader</option><option value="admin">Admin</option></select><button className="rounded-lg border px-2 py-1.5 font-bold">Save</button></form></td><td>{new Date(u.created_at).toLocaleDateString("en-AU")}</td><td>{u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString("en-AU"):"Never"}</td><td>{banned?<span className="font-bold text-red-600">Banned</span>:<span className="font-bold text-emerald-700">Active</span>}</td><td><form action={setUserBan}><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="banned" value={String(!banned)}/><button className={`rounded-lg px-3 py-1.5 font-bold ${banned?"border":"border border-red-200 text-red-600"}`}>{banned?"Unban":"Ban"}</button></form></td></tr>})}</tbody></table></div>
  </main>;
}
