import { createAdminClient } from "@/lib/supabase/admin";
import { deleteVideoChannel, upsertVideoChannel } from "../control-actions";

export default async function AdminVideos() {
  const admin = createAdminClient(); const [{ data: rows }, { data: regions }] = await Promise.all([admin.from("video_channels").select("*").order("sort_order"), admin.from("regions").select("id,name").order("name")]);
  return <main className="mx-auto max-w-6xl px-5 py-8"><h1 className="text-3xl font-black">Video channels</h1><p className="mt-2 text-gray-600">Manage publisher video channels and public feed URLs.</p>
    <form action={upsertVideoChannel} className="mt-6 grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-3"><input name="name" required placeholder="Channel name" className="rounded-lg border px-3 py-2"/><input name="channel_id" placeholder="YouTube channel ID" className="rounded-lg border px-3 py-2"/><input name="channel_url" required placeholder="Channel URL" className="rounded-lg border px-3 py-2"/><input name="feed_url" placeholder="Feed URL" className="rounded-lg border px-3 py-2"/><select name="language_code" className="rounded-lg border px-3 py-2"><option value="en">English</option><option value="si">Sinhala</option><option value="ta">Tamil</option></select><select name="region_id" className="rounded-lg border px-3 py-2"><option value="">No region</option>{(regions??[]).map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input name="sort_order" type="number" defaultValue="100" className="rounded-lg border px-3 py-2"/><label className="flex items-center gap-2"><input type="checkbox" name="enabled" defaultChecked/>Enabled</label><button className="rounded-lg bg-gray-950 px-4 py-2 font-bold text-white">Add channel</button></form>
    <div className="mt-5 space-y-3">{(rows??[]).map((r:any)=><form action={upsertVideoChannel} key={r.id} className="grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-3"><input type="hidden" name="id" value={r.id}/><input name="name" defaultValue={r.name} className="rounded-lg border px-3 py-2 font-bold"/><input name="channel_id" defaultValue={r.channel_id??""} className="rounded-lg border px-3 py-2"/><input name="channel_url" defaultValue={r.channel_url} className="rounded-lg border px-3 py-2"/><input name="feed_url" defaultValue={r.feed_url??""} className="rounded-lg border px-3 py-2"/><select name="language_code" defaultValue={r.language_code} className="rounded-lg border px-3 py-2"><option value="en">English</option><option value="si">Sinhala</option><option value="ta">Tamil</option></select><select name="region_id" defaultValue={r.region_id??""} className="rounded-lg border px-3 py-2"><option value="">No region</option>{(regions??[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="sort_order" type="number" defaultValue={r.sort_order} className="rounded-lg border px-3 py-2"/><label className="flex items-center gap-2"><input type="checkbox" name="enabled" defaultChecked={r.enabled}/>Enabled</label><div className="flex gap-2"><button className="rounded-lg bg-gray-950 px-4 py-2 text-sm font-bold text-white">Save</button><button formAction={deleteVideoChannel} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-600">Delete</button></div></form>)}</div>
  </main>;
}
