import { createClient } from "@supabase/supabase-js";
import { extractPublisherImage, verifyPublisherImage } from "../_shared/article-image.ts";

type Source={id:string;name:string;slug:string;feed_url:string|null;auto_publish:boolean;default_language_code:string;max_items_per_fetch:number;fetch_interval_minutes:number;last_fetched_at:string|null;consecutive_failures:number};
type Item={title:string;link:string;description?:string;imageUrl?:string;publishedAt?:string};
const HEADERS={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.9"};
function decodeHtml(v:string){return v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#8216;|&#8217;/g,"’").replace(/&#8220;|&#8221;/g,"”").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)));}
function clean(v?:string){if(!v)return undefined;const t=decodeHtml(v.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim());if(!t)return undefined;return t.length>700?`${t.slice(0,697).trimEnd()}...`:t;}
function attr(html:string,key:string){const e=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");for(const r of [new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']*)["']`,"i"),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${e}["']`,"i")]){const m=html.match(r);if(m?.[1])return decodeHtml(m[1].trim());}return undefined;}
function titleFromHtml(html:string){return attr(html,"og:title")??clean(html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1])??clean(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]);}
function dateFromHtml(html:string){const raw=attr(html,"article:published_time")??html.match(/["']datePublished["']\s*:\s*["']([^"']+)["']/i)?.[1]??html.match(/datetime=["']([^"']+)["']/i)?.[1];if(!raw)return undefined;const d=new Date(raw);return Number.isNaN(d.getTime())?undefined:d.toISOString();}
function canonicalizeUrl(input:string){const u=new URL(input);u.hash="";for(const k of [...u.searchParams.keys()])if(/^(utm_|fbclid$|gclid$)/i.test(k))u.searchParams.delete(k);return u.toString();}
function slugify(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"story";}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function isDue(s:Source){return !s.last_fetched_at||Date.now()-new Date(s.last_fetched_at).getTime()>=Math.max(s.fetch_interval_minutes||30,5)*60_000;}
function extractLinks(listingUrl:string,html:string,slug:string){const base=new URL(listingUrl),out=new Set<string>();for(const match of html.matchAll(/href=["']([^"'#]+)["']/gi)){try{const url=new URL(decodeHtml(match[1]),base),path=url.pathname;if(slug.startsWith("newsfirst-")&&/\/[12]\d{3}\/\d{2}\/\d{2}\//.test(path)&&/newsfirst\.lk$/i.test(url.hostname))out.add(url.toString());else if(slug.startsWith("itn-news-")&&/\/(?:ta\/)?[12]\d{3}\/\d{2}\/\d{2}\/\d+\/?$/.test(path)&&/itnnews\.lk$/i.test(url.hostname))out.add(url.toString());}catch{}}return [...out];}
async function fetchHtml(url:string){const r=await fetch(url,{headers:HEADERS,redirect:"follow",signal:AbortSignal.timeout(15_000)});if(!r.ok)throw new Error(`Page returned HTTP ${r.status}`);return await r.text();}
async function discover(source:Source):Promise<Item[]>{if(!source.feed_url)throw new Error("Source has no listing URL");const listing=await fetchHtml(source.feed_url);const links=extractLinks(source.feed_url,listing,source.slug).slice(0,source.max_items_per_fetch||15);const items:Item[]=[];for(const link of links){try{const html=await fetchHtml(link),title=titleFromHtml(html);if(!title)continue;const candidate=extractPublisherImage(html,link);const imageUrl=candidate&&await verifyPublisherImage(candidate)?candidate:undefined;items.push({title,link,description:clean(attr(html,"og:description")??attr(html,"description")),imageUrl,publishedAt:dateFromHtml(html)});}catch(e){console.error("article_metadata_failed",source.name,link,e);}}return items;}
async function processSource(supabase:ReturnType<typeof createClient>,source:Source){const run=await supabase.from("ingestion_runs").insert({source_id:source.id}).select("id").single();if(run.error)throw run.error;let fetchedCount=0,insertedCount=0,duplicateCount=0,failedCount=0,imagePendingCount=0;try{const items=await discover(source);fetchedCount=items.length;const rr=await supabase.from("source_regions").select("region_id").eq("source_id",source.id);if(rr.error)throw rr.error;const regionIds=(rr.data??[]).map(r=>r.region_id);for(const item of items){try{const can=canonicalizeUrl(item.link),hash=await sha256(`${item.title}\n${can}`);if(!item.imageUrl)imagePendingCount++;const status=source.auto_publish&&Boolean(item.imageUrl)?"published":"review_required";const ins=await supabase.from("articles").insert({source_id:source.id,title:item.title,slug:`${slugify(item.title)}-${hash.slice(0,10)}`,original_url:item.link,canonical_url:can,external_id:can,description:item.description,ai_summary:item.description,image_url:item.imageUrl??null,language_code:source.default_language_code||"en",status,auto_publish_requested:source.auto_publish,published_at:item.publishedAt??(status==="published"?new Date().toISOString():null),content_hash:hash,raw_metadata:{adapter:source.slug.startsWith("newsfirst-")?"newsfirst_html":"itn_html",image_verified:Boolean(item.imageUrl),image_pending:!item.imageUrl}}).select("id").single();if(ins.error){if(ins.error.code==="23505"){duplicateCount++;continue;}throw ins.error;}insertedCount++;if(regionIds.length){const ri=await supabase.from("article_regions").insert(regionIds.map(region_id=>({article_id:ins.data.id,region_id,confidence:1})));if(ri.error)throw ri.error;}}catch(e){failedCount++;console.error("adapter_item_failed",source.name,e);}}const now=new Date().toISOString();await supabase.from("sources").update({last_fetched_at:now,last_success_at:now,last_error_at:null,last_error_message:null,consecutive_failures:0}).eq("id",source.id);await supabase.from("ingestion_runs").update({finished_at:now,fetched_count:fetchedCount,inserted_count:insertedCount,duplicate_count:duplicateCount,failed_count:failedCount}).eq("id",run.data.id);return{source:source.name,fetchedCount,insertedCount,duplicateCount,failedCount,imagePendingCount};}catch(e){const message=e instanceof Error?e.message:String(e),now=new Date().toISOString();await supabase.from("sources").update({last_fetched_at:now,last_error_at:now,last_error_message:message.slice(0,1000),consecutive_failures:(source.consecutive_failures||0)+1}).eq("id",source.id);await supabase.from("ingestion_runs").update({finished_at:now,failed_count:Math.max(failedCount,1),error_message:message.slice(0,2000)}).eq("id",run.data.id);throw e;}}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response("Method not allowed",{status:405});const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return Response.json({error:"Missing Supabase server secrets"},{status:500});const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});let body:{sourceId?:string}={};try{body=await req.json();}catch{}let q=supabase.from("sources").select("id,name,slug,feed_url,auto_publish,default_language_code,max_items_per_fetch,fetch_interval_minutes,last_fetched_at,consecutive_failures").eq("enabled",true).eq("source_type","api");if(body.sourceId)q=q.eq("id",body.sourceId);const{data,error}=await q;if(error)return Response.json({error:error.message},{status:500});const sources=(data??[]) as Source[],due=body.sourceId?sources:sources.filter(isDue),results:unknown[]=[];for(const s of due){try{results.push(await processSource(supabase,s));}catch(e){results.push({source:s.name,error:e instanceof Error?e.message:String(e)});}}return Response.json({configuredSources:sources.length,processedSources:results.length,skippedNotDue:sources.length-due.length,results});});
