import { createClient } from "@supabase/supabase-js";

type Source = { id:string; name:string; slug:string; feed_url:string|null; auto_publish:boolean; default_language_code:string; max_items_per_fetch:number };

type Item = { title:string; link:string; description?:string; imageUrl?:string; publishedAt?:string };

const HEADERS={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.9"};

function decode(v:string){return v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");}
function clean(v?:string){if(!v)return undefined;const t=decode(v.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim());return t? (t.length>700?`${t.slice(0,697).trimEnd()}...`:t):undefined;}
function meta(html:string,key:string){const e=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");for(const r of [new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']*)["']`,"i"),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${e}["']`,"i")]){const m=html.match(r);if(m?.[1])return decode(m[1].trim());}return undefined;}
function articleDate(html:string){const raw=meta(html,"article:published_time")??html.match(/["']datePublished["']\s*:\s*["']([^"']+)["']/i)?.[1]??html.match(/datetime=["']([^"']+)["']/i)?.[1];if(!raw)return undefined;const d=new Date(raw);return Number.isNaN(d.getTime())?undefined:d.toISOString();}
function title(html:string){return meta(html,"og:title")??clean(html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1])??clean(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]);}
function slugify(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"story";}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function canonical(input:string){const u=new URL(input);u.hash="";for(const k of [...u.searchParams.keys()])if(/^(utm_|fbclid$|gclid$)/i.test(k))u.searchParams.delete(k);return u.toString();}
async function fetchHtml(url:string){const r=await fetch(url,{headers:HEADERS,redirect:"follow",signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text();}

function allowed(slug:string,url:URL){const p=url.pathname;
  if(slug==="the-morning") return p.startsWith("/articles/");
  if(slug==="asian-mirror") return p.startsWith("/news/");
  if(slug==="mawrata-news") return p.startsWith("/news/");
  if(slug==="colombo-gazette") return /^\/20\d{2}\/\d{2}\/\d{2}\//.test(p);
  return false;
}

function links(listing:string,html:string,slug:string){const base=new URL(listing);const out=new Set<string>();for(const m of html.matchAll(/href=["']([^"'#]+)["']/gi)){try{const u=new URL(decode(m[1]),base);if(u.hostname.replace(/^www\./,"")!==base.hostname.replace(/^www\./,""))continue;if(allowed(slug,u))out.add(u.toString());}catch{}}return [...out];}

async function discover(source:Source):Promise<Item[]>{if(!source.feed_url)throw new Error("Missing listing URL");const html=await fetchHtml(source.feed_url);const urls=links(source.feed_url,html,source.slug).slice(0,source.max_items_per_fetch||15);const items:Item[]=[];for(const link of urls){try{const h=await fetchHtml(link);const t=title(h);if(!t)continue;items.push({title:t,link,description:clean(meta(h,"og:description")??meta(h,"description")),imageUrl:meta(h,"og:image")??meta(h,"twitter:image"),publishedAt:articleDate(h)});}catch(e){console.error("metadata_failed",source.name,link,e);}}return items;}

async function processSource(supabase:ReturnType<typeof createClient>,source:Source){const run=await supabase.from("ingestion_runs").insert({source_id:source.id}).select("id").single();if(run.error)throw run.error;let fetched=0,inserted=0,duplicates=0,failed=0;try{const items=await discover(source);fetched=items.length;const rr=await supabase.from("source_regions").select("region_id").eq("source_id",source.id);if(rr.error)throw rr.error;const regionIds=(rr.data??[]).map(r=>r.region_id);for(const item of items){try{const can=canonical(item.link);const hash=await sha256(`${item.title}\n${can}`);const status=source.auto_publish?"published":"review_required";const ins=await supabase.from("articles").insert({source_id:source.id,title:item.title,slug:`${slugify(item.title)}-${hash.slice(0,10)}`,original_url:item.link,canonical_url:can,external_id:can,description:item.description,ai_summary:item.description,image_url:item.imageUrl,language_code:source.default_language_code||"en",status,auto_publish_requested:source.auto_publish,published_at:item.publishedAt??new Date().toISOString(),content_hash:hash,raw_metadata:{adapter:"generic_web",publisher_slug:source.slug}}).select("id").single();if(ins.error){if(ins.error.code==="23505"){duplicates++;continue;}throw ins.error;}inserted++;if(regionIds.length){const ri=await supabase.from("article_regions").insert(regionIds.map(region_id=>({article_id:ins.data.id,region_id,confidence:1})));if(ri.error)throw ri.error;}}catch(e){failed++;console.error("item_failed",source.name,e);}}const now=new Date().toISOString();await supabase.from("sources").update({last_fetched_at:now,last_success_at:now,last_error_at:null,last_error_message:null,consecutive_failures:0}).eq("id",source.id);await supabase.from("ingestion_runs").update({finished_at:now,fetched_count:fetched,inserted_count:inserted,duplicate_count:duplicates,failed_count:failed}).eq("id",run.data.id);return {source:source.name,fetched,inserted,duplicates,failed};}catch(e){const message=e instanceof Error?e.message:String(e);const now=new Date().toISOString();await supabase.from("sources").update({last_fetched_at:now,last_error_at:now,last_error_message:message.slice(0,1000),consecutive_failures:1}).eq("id",source.id);await supabase.from("ingestion_runs").update({finished_at:now,failed_count:Math.max(failed,1),error_message:message.slice(0,2000)}).eq("id",run.data.id);throw e;}}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response("Method not allowed",{status:405});const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return Response.json({error:"Missing secrets"},{status:500});const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});let body:{sourceId?:string}={};try{body=await req.json();}catch{}let q=supabase.from("sources").select("id,name,slug,feed_url,auto_publish,default_language_code,max_items_per_fetch").eq("enabled",true).eq("source_type","api").in("slug",["the-morning","asian-mirror","mawrata-news","colombo-gazette"]);if(body.sourceId)q=q.eq("id",body.sourceId);const {data,error}=await q;if(error)return Response.json({error:error.message},{status:500});const results=[];for(const s of (data??[]) as Source[]){try{results.push(await processSource(supabase,s));}catch(e){results.push({source:s.name,error:e instanceof Error?e.message:String(e)});}}return Response.json({processed:results.length,results});});
