import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/admin";
import { bulkScheduleSocial, queueRecentPublishedStories, runAutoSocialNow, updateAutoSocialConfig, updateSocialQueue } from "./actions";

export const dynamic="force-dynamic";
const PLATFORMS=["facebook","instagram","x","threads","linkedin"] as const;

export default async function SocialQueuePage(){
  const admin=createAdminClient();
  const now=new Date().toISOString();
  const [{data},{data:config},{count:queued},{count:futureScheduled},{count:failed},{count:published}]=await Promise.all([
    admin.from("social_post_queue").select("id,platform,status,post_text,created_at,scheduled_for,published_at,error_message,attempts,provider_post_id,external_url,articles(id,slug,title,image_url,published_at,sources(name))").order("created_at",{ascending:false}).limit(200),
    admin.from("social_publish_config").select("enabled,platforms,attach_article_image,timezone,max_attempts,updated_at").eq("id",1).maybeSingle(),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","queued").or(`scheduled_for.is.null,scheduled_for.lte.${now}`),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","queued").gt("scheduled_for",now),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","failed"),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","published"),
  ]);
  const rows=data??[];
  const enabledPlatforms=new Set<string>((config?.platforms??PLATFORMS) as string[]);

  return <main className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
      <div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Growth</p><h1 className="mt-1 text-3xl font-black tracking-tight">Direct social publishing</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Every public article is queued automatically. BridgeNews posts directly to the official Facebook, Instagram, Threads, X and LinkedIn APIs — no Metricool or other scheduler in the middle.</p></div>
      <div className="flex flex-wrap gap-2"><form action={runAutoSocialNow}><button className="rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white">Run publisher now</button></form><form action={queueRecentPublishedStories}><button className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black text-slate-700">Queue latest 25</button></form></div>
    </div>

    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Due now" value={queued??0}/><Metric label="Future scheduled" value={futureScheduled??0}/><Metric label="Failed" value={failed??0} attention={(failed??0)>0}/><Metric label="Published" value={published??0}/></section>

    <section className="mt-7 grid gap-5 xl:grid-cols-[1fr_.9fr]">
      <form action={updateAutoSocialConfig} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Automation</p><h2 className="mt-1 text-lg font-black">Auto-post settings</h2><p className="mt-1 text-sm leading-6 text-slate-500">When enabled, every article that becomes public and has a verified image enters the social queue automatically.</p></div><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" name="enabled" defaultChecked={config?.enabled!==false}/> Enabled</label></div>
        <div className="mt-5"><p className="text-xs font-black text-slate-700">Publish to</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{PLATFORMS.map(platform=><label key={platform} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-bold capitalize"><input type="checkbox" name={platform} defaultChecked={enabledPlatforms.has(platform)}/>{platform}</label>)}</div></div>
        <label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="attachArticleImage" defaultChecked={config?.attach_article_image!==false}/> Attach the verified article image</label>
        <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-black text-slate-600">Timezone<input name="timezone" defaultValue={config?.timezone??"Australia/Melbourne"} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-900"/></label><label className="text-xs font-black text-slate-600">Retry attempts<input name="maxAttempts" type="number" min="1" max="20" defaultValue={config?.max_attempts??5} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-900"/></label></div>
        <button className="mt-5 rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white">Save auto-post settings</button>
      </form>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Connection</p><h2 className="mt-1 text-lg font-black">Direct API credentials</h2><p className="mt-2 text-sm leading-6 text-slate-600">Credentials live only in Supabase Edge Function secrets. BridgeNews talks straight to each platform’s official publishing API.</p><div className="mt-4 rounded-xl bg-slate-50 p-4 text-xs leading-6 text-slate-600"><p className="font-black text-slate-800">Meta / Threads</p><code className="mt-1 block whitespace-pre-wrap">FACEBOOK_PAGE_ID<br/>FACEBOOK_PAGE_ACCESS_TOKEN<br/>INSTAGRAM_ACCOUNT_ID<br/>META_PAGE_ACCESS_TOKEN<br/>THREADS_USER_ID<br/>THREADS_ACCESS_TOKEN</code><p className="mt-3 font-black text-slate-800">X</p><code className="mt-1 block whitespace-pre-wrap">X_USER_ACCESS_TOKEN</code><p className="mt-3 font-black text-slate-800">LinkedIn</p><code className="mt-1 block whitespace-pre-wrap">LINKEDIN_ACCESS_TOKEN<br/>LINKEDIN_ORGANIZATION_ID<br/>LINKEDIN_VERSION</code><p className="mt-3 font-black text-slate-800">Shared</p><code className="mt-1 block whitespace-pre-wrap">BRIDGENEWS_SITE_URL<br/>META_GRAPH_VERSION</code></div><p className="mt-4 text-xs leading-5 text-slate-500">The worker runs every minute. Failed API calls retry automatically with exponential backoff and remain visible below.</p></div>
    </section>

    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Bulk posting</p><h2 className="mt-1 text-lg font-black">Schedule existing articles</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">Queue older published stories gradually instead of flooding every account at once. Each article is spaced by the interval below.</p></div>
      <form action={bulkScheduleSocial} className="mt-5 grid gap-4 xl:grid-cols-[1fr_1fr_1fr_1fr_1.5fr_auto] xl:items-end">
        <label className="text-xs font-black text-slate-600">Articles<input name="count" type="number" min="1" max="500" defaultValue="50" className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label>
        <label className="text-xs font-black text-slate-600">Look back (hours)<input name="lookbackHours" type="number" min="1" max="2160" defaultValue="168" className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label>
        <label className="text-xs font-black text-slate-600">Start delay (min)<input name="startDelay" type="number" min="0" max="1440" defaultValue="0" className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label>
        <label className="text-xs font-black text-slate-600">Spacing (min)<input name="interval" type="number" min="1" max="1440" defaultValue="10" className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label>
        <div><p className="text-xs font-black text-slate-600">Platforms</p><div className="mt-1 flex flex-wrap gap-2">{PLATFORMS.map(platform=><label key={platform} className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 py-2 text-xs font-bold capitalize"><input type="checkbox" name={`bulk_${platform}`} defaultChecked={enabledPlatforms.has(platform)}/>{platform}</label>)}</div></div>
        <button className="rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white">Bulk schedule</button>
      </form>
    </section>

    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">Latest social jobs</h2><p className="mt-1 text-xs text-slate-500">Latest 200 jobs. One queue record exists per article and platform.</p></div><div className="divide-y divide-slate-100">{rows.length?rows.map((row:any)=>{const article=Array.isArray(row.articles)?row.articles[0]:row.articles;const storyUrl=article?.slug?`/story/${article.slug}`:"/";return <article key={row.id} className="p-5"><div className="grid gap-4 lg:grid-cols-[96px_minmax(0,1fr)_220px]">{article?.image_url?<img src={article.image_url} alt="" className="h-20 w-24 rounded-xl object-cover"/>:<div className="h-20 w-24 rounded-xl bg-slate-100"/>}<div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-700">{row.platform}</span><Status value={row.status}/><span className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-black text-slate-500">{row.attempts} attempt{row.attempts===1?"":"s"}</span></div><h3 className="mt-2 font-black leading-6">{article?.title??row.post_text}</h3><p className="mt-1 text-sm text-slate-500">{article?.sources?.name??"BridgeNews"}</p>{row.scheduled_for?<p className="mt-2 text-xs text-slate-500">Due: {new Date(row.scheduled_for).toLocaleString("en-AU",{timeZone:"Australia/Melbourne"})}</p>:null}{row.provider_post_id?<p className="mt-1 truncate text-xs text-slate-400">Provider ID: {row.provider_post_id}</p>:null}{row.error_message?<p className="mt-2 rounded-xl bg-rose-50 p-3 text-xs font-semibold text-rose-700">{row.error_message}</p>:null}</div><div className="flex flex-col gap-2"><Link href={storyUrl} target="_blank" className="rounded-xl border border-slate-200 px-3 py-2 text-center text-xs font-black">Open story ↗</Link>{row.external_url?<a href={row.external_url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 px-3 py-2 text-center text-xs font-black">Open social post ↗</a>:null}{row.status==="failed"?<form action={updateSocialQueue}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="queued"/><button className="w-full rounded-xl bg-black px-3 py-2 text-xs font-black text-white">Retry now</button></form>:null}<form action={updateSocialQueue}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="skipped"/><button className="w-full rounded-xl bg-slate-100 px-3 py-2 text-xs font-black text-slate-700">Skip</button></form></div></div></article>}):<p className="p-6 text-sm text-slate-500">No social jobs yet. The next public article will create them automatically.</p>}</div></section>
  </main>;
}

function Metric({label,value,attention=false}:{label:string;value:number;attention?:boolean}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 text-3xl font-black ${attention?"text-rose-600":""}`}>{value.toLocaleString()}</p></div>}
function Status({value}:{value:string}){const cls=value==="scheduled"||value==="published"?"bg-emerald-50 text-emerald-700":value==="failed"?"bg-rose-50 text-rose-700":value==="queued"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-700";return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${cls}`}>{value}</span>}
