import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/admin";
import { queueRecentPublishedStories, runAutoSocialNow, updateAutoSocialConfig, updateSocialQueue } from "./actions";

export const dynamic="force-dynamic";
const PLATFORMS=["facebook","instagram","x","threads","linkedin"] as const;

export default async function SocialQueuePage(){
  const admin=createAdminClient();
  const [{data},{data:config},{count:queued},{count:scheduled},{count:failed},{count:published}]=await Promise.all([
    admin.from("social_post_queue").select("id,platform,status,post_text,created_at,scheduled_for,published_at,error_message,attempts,provider_post_id,articles(id,slug,title,image_url,published_at,sources(name))").order("created_at",{ascending:false}).limit(200),
    admin.from("social_publish_config").select("enabled,platforms,attach_article_image,timezone,max_attempts,updated_at").eq("id",1).maybeSingle(),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","queued"),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","scheduled"),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","failed"),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","published"),
  ]);
  const rows=data??[];
  const enabledPlatforms=new Set<string>((config?.platforms??PLATFORMS) as string[]);

  return <main className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
      <div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Growth</p><h1 className="mt-1 text-3xl font-black tracking-tight">Automatic social publishing</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Every public article is queued automatically. The social worker runs every minute and sends each post to your connected Metricool brand, which then auto-publishes it to the selected social networks.</p></div>
      <div className="flex flex-wrap gap-2"><form action={runAutoSocialNow}><button className="rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white">Run publisher now</button></form><form action={queueRecentPublishedStories}><button className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black text-slate-700">Queue latest 25</button></form></div>
    </div>

    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Waiting" value={queued??0}/><Metric label="Scheduled" value={scheduled??0}/><Metric label="Failed" value={failed??0} attention={(failed??0)>0}/><Metric label="Marked published" value={published??0}/></section>

    <section className="mt-7 grid gap-5 xl:grid-cols-[1fr_.9fr]">
      <form action={updateAutoSocialConfig} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Automation</p><h2 className="mt-1 text-lg font-black">Auto-post settings</h2><p className="mt-1 text-sm leading-6 text-slate-500">When enabled, every article that becomes public and has a verified image enters the social queue automatically.</p></div><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" name="enabled" defaultChecked={config?.enabled!==false}/> Enabled</label></div>
        <div className="mt-5"><p className="text-xs font-black text-slate-700">Publish to</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{PLATFORMS.map(platform=><label key={platform} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-bold capitalize"><input type="checkbox" name={platform} defaultChecked={enabledPlatforms.has(platform)}/>{platform}</label>)}</div></div>
        <label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="attachArticleImage" defaultChecked={config?.attach_article_image!==false}/> Attach the verified article image to social posts</label>
        <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-black text-slate-600">Timezone<input name="timezone" defaultValue={config?.timezone??"Australia/Melbourne"} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-900"/></label><label className="text-xs font-black text-slate-600">Retry attempts<input name="maxAttempts" type="number" min="1" max="20" defaultValue={config?.max_attempts??5} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-900"/></label></div>
        <button className="mt-5 rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white">Save auto-post settings</button>
      </form>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Connection</p><h2 className="mt-1 text-lg font-black">Metricool connection</h2><p className="mt-2 text-sm leading-6 text-slate-600">BridgeNews uses Metricool as the server-side publisher so one connection can fan each article out to Facebook, Instagram, X, Threads and LinkedIn. Tokens stay in Supabase Edge Function secrets, never in the browser.</p><div className="mt-4 rounded-xl bg-slate-50 p-4 text-xs leading-6 text-slate-600"><p className="font-black text-slate-800">Required Supabase secrets</p><code className="mt-2 block whitespace-pre-wrap">METRICOOL_USER_TOKEN<br/>METRICOOL_USER_ID<br/>METRICOOL_BLOG_ID<br/>BRIDGENEWS_SITE_URL</code></div><p className="mt-4 text-xs leading-5 text-slate-500">Metricool schedules each post about two minutes ahead because its scheduler API requires a future publication time. Failed jobs retry automatically with backoff.</p></div>
    </section>

    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">Latest social jobs</h2><p className="mt-1 text-xs text-slate-500">Latest 200 jobs. Queue entries are created once per article/platform, so article updates do not create duplicate posts.</p></div><div className="divide-y divide-slate-100">{rows.length?rows.map((row:any)=>{const article=Array.isArray(row.articles)?row.articles[0]:row.articles;const storyUrl=article?.slug?`/story/${article.slug}`:"/";return <article key={row.id} className="p-5"><div className="grid gap-4 lg:grid-cols-[96px_minmax(0,1fr)_220px]">{article?.image_url?<img src={article.image_url} alt="" className="h-20 w-24 rounded-xl object-cover"/>:<div className="h-20 w-24 rounded-xl bg-slate-100"/>}<div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-700">{row.platform}</span><Status value={row.status}/><span className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-black text-slate-500">{row.attempts} attempt{row.attempts===1?"":"s"}</span></div><h3 className="mt-2 font-black leading-6">{article?.title??row.post_text}</h3><p className="mt-1 text-sm text-slate-500">{article?.sources?.name??"BridgeNews"}</p>{row.scheduled_for?<p className="mt-2 text-xs text-slate-500">Scheduled: {new Date(row.scheduled_for).toLocaleString("en-AU",{timeZone:"Australia/Melbourne"})}</p>:null}{row.error_message?<p className="mt-2 rounded-xl bg-rose-50 p-3 text-xs font-semibold text-rose-700">{row.error_message}</p>:null}</div><div className="flex flex-col gap-2"><Link href={storyUrl} target="_blank" className="rounded-xl border border-slate-200 px-3 py-2 text-center text-xs font-black">Open story ↗</Link>{row.status==="failed"?<form action={updateSocialQueue}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="queued"/><button className="w-full rounded-xl bg-black px-3 py-2 text-xs font-black text-white">Retry now</button></form>:null}<form action={updateSocialQueue}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="skipped"/><button className="w-full rounded-xl bg-slate-100 px-3 py-2 text-xs font-black text-slate-700">Skip</button></form></div></div></article>}):<p className="p-6 text-sm text-slate-500">No social jobs yet. The next public article will create them automatically.</p>}</div></section>
  </main>;
}

function Metric({label,value,attention=false}:{label:string;value:number;attention?:boolean}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 text-3xl font-black ${attention?"text-rose-600":""}`}>{value.toLocaleString()}</p></div>}
function Status({value}:{value:string}){const cls=value==="scheduled"||value==="published"?"bg-emerald-50 text-emerald-700":value==="failed"?"bg-rose-50 text-rose-700":value==="queued"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-700";return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${cls}`}>{value}</span>}
