import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/admin";
import { queueHighlightedStories, updateSocialQueue } from "./actions";

export const dynamic="force-dynamic";

export default async function SocialQueuePage(){
  const admin=createAdminClient();
  const [{data},{count:queued},{count:approved},{count:published}]=await Promise.all([
    admin.from("social_post_queue").select("id,platform,status,post_text,created_at,scheduled_for,published_at,error_message,articles(id,slug,title,image_url,published_at,sources(name))").order("created_at",{ascending:false}).limit(200),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","queued"),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","approved"),
    admin.from("social_post_queue").select("id",{count:"exact",head:true}).eq("status","published"),
  ]);
  const rows=data??[];
  return <main className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Growth</p><h1 className="mt-1 text-3xl font-black tracking-tight">Social queue</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Breaking, featured and main-headline stories are queued automatically. Review them here before publishing on connected social channels.</p></div><form action={queueHighlightedStories}><button className="rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white">Queue highlighted stories</button></form></div>
  <section className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Queued" value={queued??0}/><Metric label="Approved" value={approved??0}/><Metric label="Published" value={published??0}/></section>
  <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">Latest social posts</h2><p className="mt-1 text-xs text-slate-500">Latest 200 queue records.</p></div><div className="divide-y divide-slate-100">{rows.length?rows.map((row:any)=>{const article=row.articles;const storyUrl=article?.slug?`/story/${article.slug}`:"/";return <article key={row.id} className="p-5"><div className="grid gap-4 lg:grid-cols-[96px_minmax(0,1fr)_240px]">{article?.image_url?<img src={article.image_url} alt="" className="h-20 w-24 rounded-xl object-cover"/>:<div className="h-20 w-24 rounded-xl bg-slate-100"/>}<div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-700">{row.platform}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${row.status==="published"?"bg-emerald-50 text-emerald-700":row.status==="failed"?"bg-rose-50 text-rose-700":row.status==="approved"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-700"}`}>{row.status}</span></div><h3 className="mt-2 font-black leading-6">{article?.title??row.post_text}</h3><p className="mt-1 text-sm text-slate-500">{article?.sources?.name??"BridgeNews"}</p><p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-700">{row.post_text}</p></div><div className="flex flex-col gap-2"><Link href={storyUrl} target="_blank" className="rounded-xl border border-slate-200 px-3 py-2 text-center text-xs font-black">Open story ↗</Link>{["approved","published","skipped"].map(status=><form action={updateSocialQueue} key={status}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value={status}/><button className={`w-full rounded-xl px-3 py-2 text-xs font-black ${status==="approved"?"bg-amber-50 text-amber-800":status==="published"?"bg-emerald-50 text-emerald-800":"bg-slate-100 text-slate-700"}`}>{status==="approved"?"Approve":status==="published"?"Mark published":"Skip"}</button></form>)}</div></div></article>}):<p className="p-6 text-sm text-slate-500">No social posts are queued yet. Highlight a story or use “Queue highlighted stories”.</p>}</div></section>
  <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Publishing connections</h2><p className="mt-2 text-sm leading-6 text-slate-600">The queue is production-ready, but BridgeNews does not yet have authenticated Facebook, X, Threads, LinkedIn, Telegram or WhatsApp publishing credentials connected. Until a provider is connected, this page manages approval and tracking without falsely claiming automatic publication.</p></section></main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-3xl font-black">{value.toLocaleString()}</p></div>}
