import { createAdminClient } from "@/lib/supabase/admin";
import { deleteOfficialSource, upsertOfficialSource } from "../control-actions";

export default async function AdminOfficial() {
  const admin = createAdminClient(); const [{ data: rows }, { data: regions }] = await Promise.all([admin.from("official_sources").select("*").order("sort_order"), admin.from("regions").select("id,name").order("name")]);
  const RegionOptions = ({ selected }: { selected?: string | null }) => <>{(regions ?? []).map((r:any) => <option key={r.id} value={r.id} selected={selected===r.id}>{r.name}</option>)}</>;
  return <main className="mx-auto max-w-6xl px-5 py-8"><h1 className="text-3xl font-black">Official sources</h1><p className="mt-2 text-gray-600">Manage government, emergency, transport and public-service sources shown on the site.</p>
    <form action={upsertOfficialSource} className="mt-6 grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-3"><input name="name" required placeholder="Name" className="rounded-lg border px-3 py-2"/><input name="slug" placeholder="slug" className="rounded-lg border px-3 py-2"/><input name="url" required placeholder="Official URL" className="rounded-lg border px-3 py-2"/><input name="category" placeholder="Category" className="rounded-lg border px-3 py-2"/><input name="icon" placeholder="Icon" className="rounded-lg border px-3 py-2"/><select name="region_id" className="rounded-lg border px-3 py-2"><option value="">No region</option><RegionOptions/></select><textarea name="description" placeholder="Description" className="rounded-lg border px-3 py-2 md:col-span-2"/><label className="flex items-center gap-2"><input type="checkbox" name="enabled" defaultChecked/>Enabled</label><input name="sort_order" type="number" defaultValue="100" className="rounded-lg border px-3 py-2"/><button className="rounded-lg bg-gray-950 px-4 py-2 font-bold text-white">Add source</button></form>
    <div className="mt-5 space-y-3">{(rows ?? []).map((r:any) => <form action={upsertOfficialSource} key={r.id} className="grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-3"><input type="hidden" name="id" value={r.id}/><input name="name" defaultValue={r.name} className="rounded-lg border px-3 py-2 font-bold"/><input name="slug" defaultValue={r.slug} className="rounded-lg border px-3 py-2"/><input name="url" defaultValue={r.url} className="rounded-lg border px-3 py-2"/><input name="category" defaultValue={r.category} className="rounded-lg border px-3 py-2"/><input name="icon" defaultValue={r.icon ?? ""} className="rounded-lg border px-3 py-2"/><select name="region_id" defaultValue={r.region_id ?? ""} className="rounded-lg border px-3 py-2"><option value="">No region</option>{(regions??[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><textarea name="description" defaultValue={r.description ?? ""} className="rounded-lg border px-3 py-2 md:col-span-2"/><label className="flex items-center gap-2"><input type="checkbox" name="enabled" defaultChecked={r.enabled}/>Enabled</label><input name="sort_order" type="number" defaultValue={r.sort_order} className="rounded-lg border px-3 py-2"/><button className="rounded-lg bg-gray-950 px-4 py-2 text-sm font-bold text-white">Save</button><button formAction={deleteOfficialSource} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-600">Delete</button></form>)}</div>
  </main>;
}
