import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { runOperation } from "./actions";

const OPERATIONS = [
  ["ingest-rss","RSS ingestion","Collect all enabled RSS publishers now","↻"],
  ["ingest-web","Web ingestion","Collect configured public web sources now","⌁"],
  ["ingest-generic-web","Generic web","Collect generic publisher metadata sources","◎"],
  ["backfill-source-logos","Refresh logos","Discover and improve publisher icons","◉"],
  ["backfill-images","Backfill images","Find missing public article thumbnails","▧"],
] as const;

export default async function AdminIngestion() {
  const supabase = await createClient();
  const { data } = await supabase.from("ingestion_runs").select("id,started_at,finished_at,fetched_count,inserted_count,duplicate_count,failed_count,error_message,sources(name,slug)").order("started_at", { ascending: false }).limit(100);
  const runs=data??[]; const running=runs.filter((r:any)=>!r.finished_at).length; const failed=runs.filter((r:any)=>r.error_message||Number(r.failed_count)>0).length; const inserted=runs.slice(0,20).reduce((sum:number,r:any)=>sum+Number(r.inserted_count??0),0);
  return <main className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Operations</p><h1 className="mt-1 text-3xl font-black tracking-tight">Ingestion</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Run collection and maintenance jobs manually, then review outcomes in one place.</p></div><Link href="/admin/health" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black hover:bg-slate-50">View system health →</Link></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Running" value={running} tone={running?"blue":"default"}/><Metric label="Issues in recent 100" value={failed} tone={failed?"warn":"good"}/><Metric label="Inserted in last 20 runs" value={inserted.toLocaleString()} tone="good"/></div>
    <section className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{OPERATIONS.map(([operation,title,description,icon]) => <form action={runOperation} key={operation} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md"><input type="hidden" name="operation" value={operation}/><div className="flex items-start gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-lg font-black text-indigo-600">{icon}</span><div><h2 className="font-black">{title}</h2><p className="mt-1 min-h-10 text-sm leading-5 text-slate-500">{description}</p></div></div><button className="mt-4 w-full rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white transition hover:bg-indigo-600">Run now</button></form>)}</section>
    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">History</p><h2 className="mt-1 text-lg font-black">Recent ingestion runs</h2></div><span className="text-xs font-bold text-slate-400">Latest {runs.length}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b bg-slate-50 text-left text-xs uppercase text-slate-400"><th className="p-3">Source</th><th>Started</th><th>Status</th><th>Duration</th><th>Fetched</th><th>Inserted</th><th>Duplicates</th><th>Failed</th><th>Error</th></tr></thead><tbody>{runs.map((r:any)=>{const ms=r.finished_at?new Date(r.finished_at).getTime()-new Date(r.started_at).getTime():null;const bad=r.error_message||Number(r.failed_count)>0;return <tr key={r.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/70"><td className="p-3 font-bold">{r.sources?.name??"System"}</td><td>{new Date(r.started_at).toLocaleString("en-AU")}</td><td><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${!r.finished_at?"bg-blue-50 text-blue-700":bad?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{!r.finished_at?"RUNNING":bad?"CHECK":"OK"}</span></td><td>{ms==null?"—":`${(ms/1000).toFixed(1)}s`}</td><td>{r.fetched_count}</td><td className="font-bold text-emerald-700">{r.inserted_count}</td><td>{r.duplicate_count}</td><td className={r.failed_count?"font-bold text-rose-600":""}>{r.failed_count}</td><td className="max-w-[320px] truncate text-rose-600" title={r.error_message??""}>{r.error_message??"—"}</td></tr>})}</tbody></table></div></section>
  </main>;
}
function Metric({label,value,tone="default"}:{label:string;value:string|number;tone?:"default"|"good"|"warn"|"blue"}){const c=tone==="good"?"text-emerald-600":tone==="warn"?"text-amber-600":tone==="blue"?"text-blue-600":"text-slate-950";return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 text-3xl font-black ${c}`}>{value}</p></div>}
