import { createAdminClient } from "@/lib/supabase/admin";
import { deleteArticle, updateArticle } from "../control-actions";
import { setArticleTaxonomy } from "./relationships";

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string,string> = { published:"bg-emerald-50 text-emerald-700", draft:"bg-gray-100 text-gray-600", review:"bg-amber-50 text-amber-700", rejected:"bg-red-50 text-red-700" };
  return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${styles[status] ?? "bg-gray-100 text-gray-600"}`}>{status}</span>;
}

export default async function AdminArticles({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const { q = "", status = "" } = await searchParams;
  const admin = createAdminClient();
  let query = admin.from("articles").select("id,title,description,image_url,language_code,status,published_at,sources(name)").order("published_at", { ascending: false }).limit(100);
  if (status) query = query.eq("status", status);
  if (q) query = query.ilike("title", `%${q}%`);
  const [{ data: articles }, { data: categories }, { data: topics }] = await Promise.all([
    query,
    admin.from("categories").select("id,name").order("sort_order").order("name"),
    admin.from("topics").select("id,name").order("trending_score", { ascending: false }).order("name"),
  ]);
  const articleIds = (articles ?? []).map((a: any) => a.id);
  const [{ data: articleCategories }, { data: articleTopics }] = articleIds.length ? await Promise.all([
    admin.from("article_categories").select("article_id,category_id").in("article_id", articleIds),
    admin.from("article_topics").select("article_id,topic_id").in("article_id", articleIds),
  ]) : [{ data: [] as any[] }, { data: [] as any[] }];
  const categoryMap = new Map<string, Set<string>>();
  const topicMap = new Map<string, Set<string>>();
  for (const row of articleCategories ?? []) { const set = categoryMap.get(row.article_id) ?? new Set<string>(); set.add(row.category_id); categoryMap.set(row.article_id, set); }
  for (const row of articleTopics ?? []) { const set = topicMap.get(row.article_id) ?? new Set<string>(); set.add(row.topic_id); topicMap.set(row.article_id, set); }

  return <main className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Content library</p><h1 className="mt-1 text-3xl font-black tracking-tight">Articles</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-600">Search, review and edit the stories shown on BridgeNews. Changes are reflected on the public site after save.</p></div><div className="rounded-xl bg-gray-100 px-4 py-2 text-sm font-bold text-gray-600">Showing {(articles ?? []).length} article{(articles ?? []).length===1?"":"s"}</div></div>

    <form className="mt-6 flex flex-col gap-2 rounded-2xl border border-gray-200 bg-white p-3 shadow-sm sm:flex-row"><div className="relative flex-1"><span className="pointer-events-none absolute left-3 top-2.5 text-gray-400">⌕</span><input name="q" defaultValue={q} placeholder="Search article title…" className="w-full rounded-xl border border-gray-200 bg-gray-50 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-gray-400 focus:bg-white"/></div><select name="status" defaultValue={status} className="rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm font-bold"><option value="">All statuses</option><option value="published">Published</option><option value="draft">Draft</option><option value="review">Needs review</option><option value="rejected">Rejected</option></select><button className="rounded-xl bg-gray-950 px-5 py-2.5 text-sm font-black text-white hover:bg-gray-800">Apply filter</button></form>

    <div className="mt-5 space-y-4">{(articles ?? []).map((a:any) => <article key={a.id} className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
      <div className="flex flex-col gap-4 p-5 md:flex-row"><div className="h-28 w-full shrink-0 overflow-hidden rounded-xl bg-gray-100 md:w-40">{a.image_url?<img src={a.image_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-xs font-bold text-gray-400">No image</div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={a.status}/><span className="text-xs font-bold text-gray-400">{a.sources?.name ?? "Unknown source"}</span><span className="text-xs text-gray-300">•</span><span className="text-xs text-gray-400">{a.published_at ? new Date(a.published_at).toLocaleString("en-AU") : "No publish date"}</span></div><h2 className="mt-2 text-lg font-black leading-snug">{a.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-gray-500">{a.description || "No summary available."}</p></div></div>

      <details className="border-t border-gray-100"><summary className="cursor-pointer list-none px-5 py-3 text-sm font-black text-gray-700 hover:bg-gray-50">Edit article ▾</summary><div className="border-t border-gray-100 bg-gray-50/60 p-5"><form action={updateArticle}><input type="hidden" name="id" value={a.id}/><div className="grid gap-4 xl:grid-cols-[1fr_220px]"><div className="space-y-3"><label className="block text-xs font-black uppercase tracking-wide text-gray-400">Headline<input name="title" defaultValue={a.title} className="mt-1.5 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm font-bold text-gray-900"/></label><label className="block text-xs font-black uppercase tracking-wide text-gray-400">Short description<textarea name="description" defaultValue={a.description ?? ""} rows={3} className="mt-1.5 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm normal-case tracking-normal text-gray-900"/></label><label className="block text-xs font-black uppercase tracking-wide text-gray-400">Image URL<input name="image_url" defaultValue={a.image_url ?? ""} className="mt-1.5 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm normal-case tracking-normal text-gray-900"/></label></div><div className="space-y-3"><label className="block text-xs font-black uppercase tracking-wide text-gray-400">Status<select name="status" defaultValue={a.status} className="mt-1.5 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm normal-case tracking-normal text-gray-900"><option value="published">Published</option><option value="draft">Draft</option><option value="review">Needs review</option><option value="rejected">Rejected</option></select></label><label className="block text-xs font-black uppercase tracking-wide text-gray-400">Language<select name="language_code" defaultValue={a.language_code} className="mt-1.5 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm normal-case tracking-normal text-gray-900"><option value="en">English</option><option value="si">Sinhala</option><option value="ta">Tamil</option></select></label><button className="w-full rounded-xl bg-gray-950 px-4 py-2.5 text-sm font-black text-white hover:bg-gray-800">Save article</button><button formAction={deleteArticle} className="w-full rounded-xl border border-red-200 bg-white px-4 py-2.5 text-sm font-black text-red-600 hover:bg-red-50">Delete article</button></div></div></form>
        <form action={setArticleTaxonomy} className="mt-5 grid gap-4 border-t border-gray-200 pt-5 md:grid-cols-2"><input type="hidden" name="article_id" value={a.id}/><label className="text-xs font-black uppercase tracking-wide text-gray-400">Categories<select name="category_ids" multiple defaultValue={[...(categoryMap.get(a.id) ?? [])]} className="mt-2 h-32 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm normal-case tracking-normal text-gray-900">{(categories ?? []).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-black uppercase tracking-wide text-gray-400">Topics<select name="topic_ids" multiple defaultValue={[...(topicMap.get(a.id) ?? [])]} className="mt-2 h-32 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm normal-case tracking-normal text-gray-900">{(topics ?? []).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="md:col-span-2 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-gray-500">Hold Ctrl (Windows) or Cmd (Mac) to choose multiple values.</p><button className="rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-black hover:bg-gray-50">Save categories & topics</button></div></form></div></details>
    </article>)}</div>
  </main>;
}
