import { createAdminClient } from "@/lib/supabase/admin";
import { ConfirmSubmitButton } from "@/components/admin/confirm-submit-button";
import { deleteTopic, upsertTopic } from "../control-actions";

const inputClass = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-black";

export default async function AdminTopics() {
  const admin = createAdminClient();
  const { data } = await admin.from("topics").select("id,name,slug,description,trending_score").order("trending_score", { ascending: false });
  const topics = data ?? [];

  return <main className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8 xl:px-10">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Content taxonomy</p><h1 className="mt-1 text-3xl font-black tracking-tight">Topics</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Manage curated topics and tune their manual trending priority.</p></div><span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-black text-slate-600">{topics.length} topics</span></div>

    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div className="mb-4"><h2 className="font-black text-slate-950">Add topic</h2><p className="mt-1 text-xs text-slate-500">Create a topic and optionally give it a starting trending score.</p></div><form action={upsertTopic} className="grid gap-3 md:grid-cols-[1fr_1fr_140px_auto]"><label className="text-[10px] font-black uppercase tracking-wide text-slate-400">Name<input name="name" required placeholder="Cost of living" className={`mt-1.5 ${inputClass}`}/></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-400">Slug<input name="slug" placeholder="cost-of-living" className={`mt-1.5 ${inputClass}`}/></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-400">Trending score<input name="trending_score" type="number" step="0.1" defaultValue="0" className={`mt-1.5 ${inputClass}`}/></label><button className="self-end rounded-xl bg-black px-4 py-2.5 text-sm font-black text-white hover:bg-slate-800">Add topic</button><label className="text-[10px] font-black uppercase tracking-wide text-slate-400 md:col-span-4">Description<textarea name="description" rows={2} placeholder="Optional short description" className={`mt-1.5 ${inputClass}`}/></label></form></section>

    <section className="mt-5 space-y-3">{topics.map((t:any, index:number) => <form action={upsertTopic} key={t.id} className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><input type="hidden" name="id" value={t.id}/><div className="flex items-center gap-3 border-b border-slate-100 pb-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-xs font-black text-slate-500">{index+1}</span><div className="min-w-0 flex-1"><p className="truncate font-black text-slate-950">{t.name}</p><p className="mt-0.5 text-xs text-slate-400">/{t.slug}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">Score {Number(t.trending_score ?? 0).toFixed(1)}</span></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_140px]"><label className="text-[10px] font-black uppercase tracking-wide text-slate-400">Name<input name="name" defaultValue={t.name} className={`mt-1.5 ${inputClass} font-bold`}/></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-400">Slug<input name="slug" defaultValue={t.slug} className={`mt-1.5 ${inputClass}`}/></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-400">Trending score<input name="trending_score" type="number" step="0.1" defaultValue={t.trending_score} className={`mt-1.5 ${inputClass}`}/></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-400 md:col-span-3">Description<textarea name="description" rows={2} defaultValue={t.description ?? ""} className={`mt-1.5 ${inputClass}`}/></label></div><div className="mt-4 flex flex-col-reverse gap-2 border-t border-slate-100 pt-4 sm:flex-row sm:justify-end"><ConfirmSubmitButton formAction={deleteTopic} label="Delete" confirmMessage={`Delete topic ${t.name}?`} className="rounded-xl border border-rose-200 bg-white px-4 py-2.5 text-sm font-black text-rose-600 hover:bg-rose-50"/><button className="rounded-xl bg-black px-5 py-2.5 text-sm font-black text-white hover:bg-slate-800">Save changes</button></div></form>)}</section>
  </main>;
}
