create table if not exists public.site_settings (
  key text primary key,
  group_name text not null default 'general',
  label text not null,
  description text,
  value jsonb not null default 'null'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.homepage_sections (
  id uuid primary key default gen_random_uuid(),
  section_key text not null unique,
  label text not null,
  enabled boolean not null default true,
  sort_order integer not null default 100,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.video_channels (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  channel_id text,
  channel_url text not null,
  feed_url text,
  language_code text not null default 'en',
  region_id uuid references public.regions(id) on delete set null,
  enabled boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.official_sources (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  url text not null,
  category text not null default 'General',
  description text,
  icon text,
  region_id uuid references public.regions(id) on delete set null,
  enabled boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;
alter table public.homepage_sections enable row level security;
alter table public.video_channels enable row level security;
alter table public.official_sources enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on public.site_settings, public.homepage_sections, public.video_channels, public.official_sources, public.admin_audit_log from anon, authenticated;
grant select on public.site_settings, public.homepage_sections, public.video_channels, public.official_sources to anon, authenticated;

create policy "public read site settings" on public.site_settings for select to anon, authenticated using (true);
create policy "public read homepage sections" on public.homepage_sections for select to anon, authenticated using (true);
create policy "public read enabled video channels" on public.video_channels for select to anon, authenticated using (enabled = true);
create policy "public read enabled official sources" on public.official_sources for select to anon, authenticated using (enabled = true);

insert into public.homepage_sections(section_key,label,enabled,sort_order) values
 ('region_switcher','Region switcher',true,10),('top_stories','Top stories',true,20),('weather','Weather',true,30),('fast_scan','In the News',true,40),('stats','Statistics',true,50),('source_rail','Source rail',true,60),('trending_categories','Trending categories',true,70),('latest_news','Latest news',true,80),('most_covered','Most covered',true,90),('quick_links','Quick links',true,100),('regional_sections','Regional sections',true,110)
on conflict (section_key) do nothing;

insert into public.site_settings(key,group_name,label,description,value) values
 ('site_name','branding','Site name','Public website name','"BridgeNews"'::jsonb),('default_region','homepage','Default homepage region','Region selected when no query parameter is present','"sri-lanka"'::jsonb),('ticker_enabled','homepage','Live ticker','Show the live news ticker','true'::jsonb),('markets_enabled','homepage','Markets strip','Show the exchange-rate strip','true'::jsonb),('maintenance_mode','system','Maintenance mode','Reserved switch for a future maintenance screen','false'::jsonb)
on conflict (key) do nothing;

with r as (select id from public.regions where slug='sri-lanka' limit 1)
insert into public.official_sources(name,slug,url,category,description,icon,region_id,sort_order)
select * from (values
 ('Department of Meteorology','meteorology','https://meteo.gov.lk/index','Weather','Weather forecasts, advisories and observations','🌦️',(select id from r),10),
 ('Disaster Management Centre','dmc','https://www.dmc.gov.lk/','Emergency','Disaster alerts and emergency information','⚠️',(select id from r),20),
 ('Sri Lanka Police','police','https://www.police.gov.lk/','Public Safety','Police news, releases and public services','👮',(select id from r),30),
 ('Sri Lanka Railways','railways','https://www.railway.gov.lk/web/','Transport','Railway notices and passenger information','🚆',(select id from r),40),
 ('Ceylon Electricity Board','ceb','https://www.ceb.lk/','Utilities','Power-sector notices and electricity information','⚡',(select id from r),50),
 ('Central Bank of Sri Lanka','cbsl','https://www.cbsl.gov.lk/','Finance','Monetary policy, exchange rates and financial releases','🏦',(select id from r),60)
) as v(name,slug,url,category,description,icon,region_id,sort_order)
on conflict (slug) do nothing;