create table if not exists public.traffic_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view','outbound_click','social_share','newsletter_signup')),
  path text not null,
  referrer_host text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  session_id text,
  article_id uuid references public.articles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists traffic_events_occurred_at_idx on public.traffic_events (occurred_at desc);
create index if not exists traffic_events_type_occurred_idx on public.traffic_events (event_type, occurred_at desc);
create index if not exists traffic_events_path_occurred_idx on public.traffic_events (path, occurred_at desc);
create index if not exists traffic_events_source_occurred_idx on public.traffic_events (utm_source, occurred_at desc) where utm_source is not null;
alter table public.traffic_events enable row level security;

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  status text not null default 'active' check (status in ('active','unsubscribed')),
  preferences jsonb not null default '{"regions":["sri-lanka","australia","international"],"frequency":"daily"}'::jsonb,
  source text not null default 'website',
  subscribed_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  updated_at timestamptz not null default now()
);
create unique index if not exists newsletter_subscribers_email_lower_uidx on public.newsletter_subscribers (lower(email));
create index if not exists newsletter_subscribers_status_idx on public.newsletter_subscribers (status, subscribed_at desc);
alter table public.newsletter_subscribers enable row level security;

create table if not exists public.social_post_queue (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  platform text not null check (platform in ('facebook','x','threads','linkedin','telegram','whatsapp')),
  status text not null default 'queued' check (status in ('queued','approved','published','skipped','failed')),
  post_text text,
  scheduled_for timestamptz,
  published_at timestamptz,
  external_url text,
  attempts integer not null default 0 check (attempts >= 0),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (article_id, platform)
);
create index if not exists social_post_queue_status_idx on public.social_post_queue (status, scheduled_for nulls first, created_at desc);
create index if not exists social_post_queue_article_idx on public.social_post_queue (article_id);
alter table public.social_post_queue enable row level security;

create or replace function public.queue_bridge_news_social_posts()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'published'
     and new.image_url is not null
     and (coalesce(new.is_breaking,false) or coalesce(new.is_featured,false) or coalesce(new.is_main_headline,false)) then
    insert into public.social_post_queue(article_id, platform, post_text)
    select new.id, p, new.title
    from unnest(array['facebook','x','threads','telegram']::text[]) p
    on conflict (article_id, platform) do nothing;
  end if;
  return new;
end;
$$;
revoke all on function public.queue_bridge_news_social_posts() from public;
drop trigger if exists queue_bridge_news_social_posts_trigger on public.articles;
create trigger queue_bridge_news_social_posts_trigger
after insert or update of status,is_breaking,is_featured,is_main_headline,image_url on public.articles
for each row execute function public.queue_bridge_news_social_posts();
